name: Rebuild LLVM 14.0

on:
  push:
    branches:
      - main
      - '**rebuild_llvm**'
    paths:
      - "llvm_patches/*14_0*"
      - "alloy.py"
      - ".github/workflows/rebuild-llvm14.yml"
  workflow_dispatch:

jobs:
  linux-build:
    uses: ./.github/workflows/reusable.build.yml
    with:
      worker: ubuntu-latest
      release_build: false
      llvm_version: "14.0"
      os: linux

  linux-build-rel:
    uses: ./.github/workflows/reusable.build.yml
    with:
      worker: ubuntu-latest
      release_build: true
      llvm_version: "14.0"
      os: linux

  win-build:
    uses: ./.github/workflows/reusable.build.yml
    with:
      worker: 'windows-2019'
      release_build: false
      llvm_version: "14.0"
      os: win
